Fix typo in "Faux has_one" guide
graphiti-api/graphiti-api.github.io pull request #43
Opened 2022-02-15 19:39 UTC by jelaniwoods

I noticed this typo while reading the docs. Here's a small PR to fix it.

2022-07-20 08:22 UTC, Zooip approved these changes

2022-07-20 08:45 UTC, Zooip requested changes
You have to compile your changes first (see Readme.md)

2022-07-20 08:53 UTC, Zooip approved these changes
Nevermind, it's done in CI, my bad.

2022-11-19 22:23 UTC, jelaniwoods commented
@Zooip is there anything else I need to do for this PR? Or can it be merged?

2022-11-20 07:49 UTC, Zooip commented
It can be merged as far as I know

2026-06-18 14:18 UTC, merged